export interface GlossaryTerm {
  term: string;
  definition: string;
  explanation: string;
  relatedTerms: string[];
  example: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { term: 'Throughput', definition: 'Number of requests or messages a component can process per second.', explanation: 'Throughput is your volume metric: how much work the system can sustain over time. High throughput systems are engineered to parallelize work and reduce per-request overhead.\n\nThroughput is not enough by itself. A component can have high throughput but poor latency, so always pair it with latency and error-rate metrics.', relatedTerms: ['Latency', 'Capacity', 'Utilization'], example: 'A Redis cache serving 120k GET requests per second.' },
  { term: 'Latency', definition: 'Time required to process a single request from start to finish.', explanation: 'Latency is user-perceived responsiveness and is usually measured as P50/P95/P99, not just average. Tail latency matters because it captures worst-case user experience.\n\nEnd-to-end latency includes network hops, queueing delay, processing time, and downstream dependencies.', relatedTerms: ['Throughput', 'Bottleneck', 'Circuit Breaker'], example: 'Checkout API P95 latency is 180 ms during peak.' },
  { term: 'Capacity', definition: 'Maximum sustainable load before a component starts dropping or timing out requests.', explanation: 'Capacity is a limit, not a target. Good designs run below hard capacity with headroom for spikes and failures.\n\nCapacity planning includes CPU, memory, connections, and disk I/O limits, not only request counts.', relatedTerms: ['Utilization', 'Horizontal Scaling', 'Vertical Scaling'], example: 'A service can safely handle 8k concurrent websocket connections per pod.' },
  { term: 'Utilization', definition: 'Current load as a percentage of available capacity.', explanation: 'Utilization shows how close a component is to saturation. Sustained high utilization increases queueing, latency, and failure probability.\n\nMany teams alert on utilization thresholds (for example, 70% warning, 85% critical) to scale before incidents.', relatedTerms: ['Capacity', 'Bottleneck', 'Backpressure'], example: 'Database CPU at 88% for 10 minutes.' },
  { term: 'Bottleneck', definition: 'The slowest component that limits the performance of the whole system.', explanation: 'In a pipeline, overall throughput is constrained by the weakest stage. Upgrading non-bottleneck components does little until the true bottleneck is addressed.\n\nBottlenecks can move over time, especially after scaling one layer.', relatedTerms: ['Throughput', 'Latency', 'Utilization'], example: 'API servers are idle while a single DB shard is overloaded.' },
  { term: 'Horizontal Scaling', definition: 'Increasing capacity by adding more instances of a component.', explanation: 'Horizontal scaling spreads traffic across many nodes and improves fault tolerance. It is the default approach for stateless services.\n\nIt requires load balancing, service discovery, and data partitioning or replication strategies.', relatedTerms: ['Vertical Scaling', 'Load Balancing', 'Replication'], example: 'Scale service from 8 pods to 32 pods behind a load balancer.' },
  { term: 'Vertical Scaling', definition: 'Increasing capacity by making one instance bigger (more CPU, RAM, IOPS).', explanation: 'Vertical scaling is simple and fast for early growth but has a hard ceiling and can increase blast radius.\n\nMature systems combine vertical and horizontal scaling depending on workload characteristics.', relatedTerms: ['Horizontal Scaling', 'Capacity'], example: 'Upgrade database node from 8 vCPU to 32 vCPU.' },
  { term: 'Single Point of Failure (SPOF)', definition: 'A component whose failure can take down the whole system.', explanation: 'SPOFs reduce availability because there is no redundant path when that component fails. They commonly appear in databases, gateways, or networking tiers.\n\nEliminating SPOFs means adding redundancy and automated failover.', relatedTerms: ['Failover', 'Replication', 'Load Balancing'], example: 'Only one API gateway instance serves all production traffic.' },
  { term: 'Replication', definition: 'Maintaining copies of data or services across multiple nodes.', explanation: 'Replication improves availability and read scale by creating additional copies. Data replication can be synchronous or asynchronous, each with latency/consistency tradeoffs.\n\nService replication (multiple instances) also improves resilience when combined with health checks.', relatedTerms: ['Read Replica', 'Failover', 'CAP Theorem'], example: 'Primary DB with three replicas across zones.' },
  { term: 'Sharding', definition: 'Splitting data across multiple nodes using a partition key.', explanation: 'Sharding increases write throughput and dataset size by distributing load. Correct shard key design is critical to avoid hotspots.\n\nCross-shard queries and transactions become more complex as shard count grows.', relatedTerms: ['Replication', 'Capacity', 'CAP Theorem'], example: 'Users sharded by user_id modulo shard count.' },
  { term: 'CAP Theorem', definition: 'Distributed systems can provide at most two of consistency, availability, and partition tolerance during a network partition.', explanation: 'Because partitions are inevitable, real systems choose tradeoffs between consistency and availability when communication fails.\n\nCAP is about partition scenarios specifically, not normal operation; interview answers should note this nuance.', relatedTerms: ['Eventual Consistency', 'Replication', 'Sharding'], example: 'Dynamo-style systems favor availability and eventual consistency under partitions.' },
  { term: 'Load Balancing', definition: 'Distributing requests across multiple backends to improve performance and availability.', explanation: 'Load balancing evens traffic and enables horizontal scaling. Algorithms like round robin or least connections change behavior under uneven workloads.\n\nLoad balancers rely on health checks so traffic avoids unhealthy instances.', relatedTerms: ['Horizontal Scaling', 'Health Check', 'Failover'], example: 'Nginx balances API traffic across 12 service instances.' },
  { term: 'Circuit Breaker', definition: 'Resilience pattern that stops calls to failing dependencies to prevent cascading outages.', explanation: 'When downstream errors exceed thresholds, a circuit breaker opens and short-circuits requests for a cooldown period.\n\nThis protects thread pools and latency budgets while dependencies recover.', relatedTerms: ['Failover', 'Latency', 'Bottleneck'], example: 'Service returns fallback data when payment provider circuit is open.' },
  { term: 'Rate Limiting', definition: 'Controlling how frequently clients can send requests in a time window.', explanation: 'Rate limits protect infrastructure from abuse and accidental overload while preserving fairness among tenants.\n\nDesign choices include dimensions (IP, user, API key), window type, and response behavior.', relatedTerms: ['Backpressure', 'Capacity', 'AuthService'], example: 'Public API allows 100 requests per minute per key.' },
  { term: 'Backpressure', definition: 'Mechanism that slows producers when consumers cannot keep up.', explanation: 'Backpressure prevents unbounded queue growth and resource exhaustion. It can be implemented via rate limiting, bounded queues, and flow-control signals.\n\nWithout it, latency and failure rates climb rapidly during bursts.', relatedTerms: ['Queue', 'Throughput', 'Utilization'], example: 'Consumers pause Kafka fetches when processing lag is high.' },
  { term: 'Idempotency', definition: 'Property where repeating the same operation yields the same result.', explanation: 'Idempotency makes retries safe for unreliable networks and async processing. It is essential in payment, booking, and message-processing systems.\n\nCommon techniques are idempotency keys and deduplication stores.', relatedTerms: ['Queue', 'Dead Letter Queue', 'Retry'], example: 'POST /payments uses an idempotency key to avoid double charge.' },
  { term: 'Eventual Consistency', definition: 'Data replicas may temporarily differ but converge over time.', explanation: 'Eventual consistency improves availability and write latency in distributed systems, but clients may observe stale reads.\n\nDesigns often include read-repair, versioning, and user-facing messaging for temporary inconsistency.', relatedTerms: ['CAP Theorem', 'Replication', 'Read Replica'], example: 'New profile photo appears globally within a few seconds.' },
  { term: 'Cache Invalidation', definition: 'Process of removing or updating stale entries in cache.', explanation: 'Invalidation keeps cached data aligned with source of truth after writes. Strategies include TTL expiry, write-through updates, and event-driven deletes.\n\nPoor invalidation causes stale or inconsistent user experience.', relatedTerms: ['Cache', 'Eventual Consistency', 'TTL'], example: 'Invalidate user profile cache on profile update event.' },
  { term: 'Read Replica', definition: 'Replica database node dedicated primarily to serving read queries.', explanation: 'Read replicas reduce load on primaries and improve read scalability. They are usually asynchronous and can lag behind the primary.\n\nApplications must route stale-tolerant reads appropriately.', relatedTerms: ['Replication', 'Database', 'Eventual Consistency'], example: 'Analytics read queries routed to replica cluster.' },
  { term: 'Write-Ahead Log (WAL)', definition: 'Durability technique where changes are logged before being applied to data files.', explanation: 'WAL ensures crash recovery by replaying committed operations after restart. It also supports replication streams in many databases.\n\nLog throughput and disk behavior often become key performance constraints.', relatedTerms: ['Replication', 'Database', 'Durability'], example: 'PostgreSQL replays WAL after restart to recover committed transactions.' },
  { term: 'Dead Letter Queue', definition: 'Queue that stores messages that repeatedly fail processing.', explanation: 'DLQs isolate problematic messages so normal traffic continues. They enable debugging and controlled replay after fixes.\n\nA DLQ without alerting and replay tooling is a hidden reliability risk.', relatedTerms: ['Queue', 'Backpressure', 'Idempotency'], example: 'Failed order events moved to DLQ after 5 retries.' },
  { term: 'Health Check', definition: 'Probe that periodically verifies component liveness or readiness.', explanation: 'Health checks allow orchestrators and load balancers to remove unhealthy instances quickly. Readiness checks should include dependency checks when needed.\n\nOverly strict checks can cause flapping; overly weak checks can route traffic to broken nodes.', relatedTerms: ['Failover', 'Load Balancing', 'SPOF'], example: 'Kubernetes readiness probe checks DB connectivity before serving traffic.' },
  { term: 'Failover', definition: 'Automatic switch from a failed component to a healthy backup.', explanation: 'Failover reduces downtime by promoting standbys or rerouting traffic when primary paths fail. It depends on fast detection and tested automation.\n\nTradeoffs include recovery time objective (RTO) and data loss objective (RPO).', relatedTerms: ['Replication', 'Health Check', 'SPOF'], example: 'DNS shifts traffic to secondary region during outage.' },
  { term: 'Cold Start', definition: 'Startup delay before a serverless function handles its first request.', explanation: 'Cold starts happen when runtime environments are not already warm. They add tail latency, especially in low-traffic or bursty workloads.\n\nMitigations include provisioned concurrency and minimizing package size.', relatedTerms: ['Lambda', 'Latency'], example: 'First invocation after idle has 400 ms extra delay.' },
  { term: 'Connection Pooling', definition: 'Reusing pre-opened connections instead of creating one per request.', explanation: 'Pooling reduces connection setup overhead and protects databases from connection storms. Pool size tuning must match DB limits and app concurrency.\n\nMisconfigured pools can cause timeouts or starve other services.', relatedTerms: ['Database', 'Latency', 'Capacity'], example: 'API uses pgBouncer with 100 pooled connections.' },
  { term: 'Fan-out', definition: 'One producer sends data or requests to many downstream consumers.', explanation: 'Fan-out is common in event-driven systems where one event triggers multiple side effects. It enables extensibility but can amplify load quickly.\n\nControl with backpressure, retries, and per-subscriber isolation.', relatedTerms: ['PubSub', 'EventBus', 'Backpressure'], example: 'OrderCreated event triggers billing, inventory, and notifications.' },
  { term: 'Fan-in', definition: 'Many producers send data into a single downstream component.', explanation: 'Fan-in concentrates load and often creates bottlenecks at aggregators or databases. Partitioning, buffering, and autoscaling are common mitigations.\n\nObservability is crucial because upstream issues appear as downstream saturation.', relatedTerms: ['Bottleneck', 'Queue', 'Capacity'], example: 'Many edge services push logs into one central collector.' },
];

export const GLOSSARY_BY_TERM = new Map(GLOSSARY_TERMS.map((t) => [t.term, t] as const));
